#!/bin/sh

mkdir -p ~/.vim/tmp/undo
git clone https://github.com/MarcWeber/vim-addon-manager ~/.vim/vad

# vim
echo 'so $HOME/tools/vimrc' > ~/.vimrc

# zsh
echo 'source ~/tools/zshrc' > ~/.zshrc

# git
echo '[include] \
    path = /path/to/file' > ~/.gitconfig

# Awesome
mkdir -p ~/.config/awesome
echo 'dofile("~/tools/awesome/rc.lua")' > ~/.config/awesome/rc.lua
